### ISSUE TITLE
Support SSPI (smartcard/passwordless authentication) for proxies

### ISSUE THREAD

**Issue by voltagex** [bruderstein/nppPluginManager#1]
Hey, I noticed you were using cURL internally. Would it be possible for you to add in the functions needed so that the Plugin Manager can authenticate against some corporate proxies?

**Comment by voltagex** [comment]
Years later, curl builds for windows support NTLM-SSPI. I've long since moved on to other text-editors though. I'll reopen if anyone is interested.

**Comment by bruderstein** [comment]
Sorry, didn't realise this was still open. Since version 1.3 Plugin Manager has used the InternetOpen() etc API from Win32/IE, and hence supports all proxies that Windows/IE supports.

**Comment by voltagex** [comment]
Thanks for the clarification - was just cleaning out my old issues.
