### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by h4uja2** [bruderstein/nppPluginManager#101]
### Description of the Issue
I get this eror: Installation of "plugin name here" failed
Whenever I try to install, update or reinstall any plugin, except for Autosave. This one can be installed without any issues.

I did a fresh install of npp and pm, tried both x86 and x64, launched and installed as administrator. No changes.

**Comment by h4uja2** [comment]
Screenshot of error: https://i.imgur.com/A9Yi4Y2.png

Manual installation works. Reinstalling manually installed plugins gives same error.

**Comment by chcg** [comment]
@h4uja2 
Which version of windows are you using? 
Could you check your TLS version, see #98

**Comment by h4uja2** [comment]
Windows 10. Enabling TLS 1.1 and TLS 1.2 fixed the issue. Thanks
