### ISSUE TITLE
plugin manager does not appear in plugins menu, npp v7.5.5 64bit

### ISSUE THREAD

**Issue by qt3m45su0najc7** [bruderstein/nppPluginManager#102]
Installed v7.5.5 64bit, menu bar shows plugins, but the plugin manager is not displayed and did not see it in preferences.  Re-ran as Administrator, no change.
![untitled](https://user-images.githubusercontent.com/465722/37220961-e47b015e-238d-11e8-9db3-6069dee32883.png)

OS Name	Microsoft Windows 10 Home
Version	10.0.16299 Build 16299

**Comment by bruderstein** [comment]
You need to install it separately - download it from the releases tab here.. It doesn't come bundled with Notepad++ any more.

**Comment by qt3m45su0najc7** [comment]
ok. thank you.
