### ISSUE TITLE
NPP fails to recognize PluginManager DLL

### ISSUE THREAD

**Issue by ericscoles** [bruderstein/nppPluginManager#103]
### Description of the Issue

Trying unsuccessfully to install PluginManager on a new install of NPP (64bit) on Windows 10. 

### Steps to Reproduce the Issue

1. install 64bit NPP
2. extract PluginManager.dll & copy to Notepad++\plugins
3. extract gpup.exe & copy to Notepad++\updater
4. restart NPP. 

### Expected Behavior

PluginManager is available on Plugins menu

### Actual Behavior

PluginManager is not available on Plugins menu

### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

nppPluginManager version: PluginManager_v1.4.9_x64

Also tried using Settings > Import > Import Plugin(s). Tried doing this several different ways, since documentation is unclear on where the plugin DLL should be located when it's 'imported'; doesn't seem to do anything. 

Tried running NPP as Administrator. No change in behavior. 

Note: No errors are returned.

**Comment by ericscoles** [comment]
Closing this issue - I'm uninstalling 64bit & using 32bit instead. Not resolved.

**Comment by bruderstein** [comment]
The author of notepad++ has decided not to include plugin manager with n++ any more.

To install plugin manager, just copy the pluginmanager.dll to c:\program files (x86)\notepad++\plugins, and the gpup.exe to c:\program files (x86)\notepad++\updater.

**Comment by ericscoles** [comment]
Thanks, but that doesn't address the issue, which was that plugin manager wouldn't **install** after performing exactly those steps (see above). 

The only way I found to successfully address the issue was to uninstall the 64bit version of NPP, install the 32bit version, and then manually install Plugin Manager.

**Comment by bruderstein** [comment]
There is no install. You just have to copy the files and restart notepad++. Import plugin doesn't work (I think that's only for language definitions).

**Comment by bruderstein** [comment]
For the x64 version, make sure you're copying the files to the notepad++ directory in `c:\program files` (not "program files (x86)"

**Comment by ericscoles** [comment]
As noted in OP, did all those things.

I get that you think this is just someone not following instructions. I'm an IT professional with almost 30 years of experience, a number of those on help desks. I tried a number of different combinations. As noted in the OP, the issue was that NPP did not recognize the existence of the plugin.
