### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by choueis** [bruderstein/nppPluginManager#106]
I can see a plugin list in Plugin Manager. But when I choose any one of them to install, I got an error saying Installation of (plugin name) failed. I tried to run Notepad++ as an administrator, but it didn't take effect. Also, I tried to add current windows user to Notepad++ folder with full control permission, but it didn't take effect either. 

Plugin Manager: 1.4.11
Notepad++: 7.5.5 x64

**Comment by h4uja2** [comment]
Enable TLS 1.1 and 1.2
see [#98](https://github.com/bruderstein/nppPluginManager/issues/98)

**Comment by chcg** [comment]
See https://github.com/libgit2/libgit2/commit/5ecb62206a9cdb6cb2105f5ef6cfcd3b9f5bab3a how to enable tls from source within service.

**Comment by bruderstein** [comment]
@chcg would putting this code in plugin manager itself help?

**Comment by choueis** [comment]
Thanks for the comments. It works.
