### ISSUE TITLE
Plugins list - update issue

### ISSUE THREAD

**Issue by jcaillon** [bruderstein/nppPluginManager#109]
### Description of the Issue

Hi, there seems to be an issue with list of the x32 plugins.

The development list is up to date but the "normal" list hasn't been updated recently, at least not in the last 26 days.

![image](https://user-images.githubusercontent.com/11553075/38163978-4245305e-34fd-11e8-8a5e-a1fbda4d1542.png)

3P plugin updated in 2018-03-05 to v1.8.1.

[dev list](http://nppxmldev.bruderste.in/pm/xml/plugins.zip) contains v1.8.1 ->ok
[normal list](http://nppxml.bruderste.in/pm/xml/plugins.zip) still contains the old version v1.7.7

Best regards

**Comment by bruderstein** [comment]
Thanks, I'll take a look

**Comment by chcg** [comment]
Lists synced again.
