### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [bruderstein/nppPluginManager#111]
Hello! I want to contribute on your project with making logo design. What do you think about it? It can be logotype . If you interested we can talk about design choices. I am waiting your feedback! 😀

Best Regards,
Arslan Şahin 
Graphics Designer

**Comment by bruderstein** [comment]
Sounds awesome! I have zero design ability, not sure about @chcg, so I'd say just go for it and make a suggestion!

**Comment by chcg** [comment]
My design abilities are also at level zero. So also fine for me.

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1hSxmVFQ787eRg7tXjokL30TVWp2W4sOI?usp=sharing
Hi I made the logo design.I hope you like it...

**Comment by chcg** [comment]
Thoughts about the usage:
- readme.md
- about box (+ unrelated feature: link to this repo)
- ? plugin menu in N++ in front of PM name, unsure if this is possible
- own entry to menu bar, not available yet
- what about hires displays? I have not worked with that yet and I'm not sure if and how PM is notified about changes (see https://msdn.microsoft.com/en-us/library/windows/desktop/mt843498(v=vs.85).aspx)

**Comment by timonss** [comment]
Do you need a logo ?. Maybe I can help you and give you a logo for free.
