### ISSUE TITLE
Cann't install plugins from github

### ISSUE THREAD

**Issue by imbear** [bruderstein/nppPluginManager#114]
### Description of the Issue

A strange problem.
I cann't install plugins from github, but can install plugins from somewhere else, e.g., sourceforge.net.

I can visit github and download something directly.

### Steps to Reproduce the Issue

1.  Open the Plugin Manager
2.  Install plugin from github

### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : E:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 

![notepad _2018-05-26_05-50-31](https://user-images.githubusercontent.com/2120811/40567617-c64f3abc-60a8-11e8-8a7d-f7c697ad984e.png)

![notepad _2018-05-26_05-50-07](https://user-images.githubusercontent.com/2120811/40567623-cda14bf2-60a8-11e8-8132-97d5e7356d58.png)

![2018-05-26_05-43-07](https://user-images.githubusercontent.com/2120811/40567454-f6662324-60a7-11e8-9370-083531957383.png)

**Comment by L1cardo** [comment]
same problem

**Comment by chcg** [comment]
@imbear @L1cardo 
Can't reproduce this issue with code alignment and dspell on win10.
Could you check if the download is possible with IE. See also https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/. Could you check that for schannnel TLS 1.1 and 1.2 is enabled.

**Comment by imbear** [comment]
My Internet Options, "TLS 1.2" is Unchecked!
Check it, and I can install plugins from github.

Thanks!

**Comment by TBugReporter** [comment]
OMG!  I've been suffering from this - manually dissecting the install instructions in the XML file and following those instructions by hand - for almost a year!  Why hasn't this tweak been more widely disseminated, for those among us who wouldn't normally touch IE with a ten foot pole?

**Comment by felix-kolbe** [comment]
Same problem, **next solution**: SSL & TLS had all been enabled (forced by user profiles) in my 'internet options', but still I couldn't access github.com.
Finally, I found my solution: Enable this option which is about 10 checkboxes above SSL and named like '**Warn when switching between secure and unsecure mode.'** -- rough translation from "_Beim Wechsel zwischen sicherem und nicht sicherem Modus warnen_."

I didn't get any warning, but github.com could be accessed from IE and NPP. Surprisingly, I had to enable it again after two weeks or after switching to NPPx86...
