### ISSUE TITLE
https certificate expired for https://bruderste.in/npp/pm/

### ISSUE THREAD

**Issue by ErwanLeroux** [bruderstein/nppPluginManager#115]
Hello, the https certificate expired for https://bruderste.in/npp/pm/ has expired today 26/05/2018

I opened an issue here because the listed email doesn't work.

**Comment by chcg** [comment]
@bruderstein Could you please take care of the update. Thanks.

**Comment by bruderstein** [comment]
Done. And hopefully setup the renew hook properly so it won't happen again.

**Comment by chcg** [comment]
@bruderstein See https://notepad-plus-plus.org/community/topic/16086/32-bit-plugin-admin-system-s-server-causes-sec_error_expired_certificate, issue is happening again.
