### ISSUE TITLE
Add "Install PluginManager" Menu in Notepad++

### ISSUE THREAD

**Issue by firulais** [bruderstein/nppPluginManager#123]
### Description of the Issue
Add "Install PluginManager" Menu in Notepad++

### Steps to Reproduce the Issue
PluginManager is a valuable tool for every person that isn't a developer or core IT user.

### Expected Behavior
After pressing "Install PluginManager" the needed files are downloaded and copied by the program into the correct folder. After restart of Notepad++ the PluginManger is visible.

### Actual Behavior
Download, unzip, copy, restart.

**Comment by sm4rk0** [comment]
Nice idea, but this issue/feature request should be reported [here](https://github.com/notepad-plus-plus/notepad-plus-plus).

**Comment by chcg** [comment]
Situation is still unchanged and just a manual installation of PM is possible until N++ contains a replacement.
Also there is some discussion on removing the ad at https://github.com/bruderstein/nppPluginManager/issues/80. I don't expect a solution in the near future.
