### ISSUE TITLE
Critical - DEV plugin list failing to load due to bad MD5 hash

### ISSUE THREAD

**Issue by CollinChaffin** [bruderstein/nppPluginManager#132]
The DEV plugin list fails to load because the MD5 from the url in the header of `https://nppxmldev.bruderste.in/pm/xml/plugins2.md5.txt` is returning `850c71329759e892f83dcb0b82fef2b4` but the latest zip MD5 is really `f8f0e661d4cc5ef564cd0a9e54057dd6`, which does not tell the user this via the returned error, but instead kind of erroneously just falls back to indicating a connectivity issue which causes further confusion.  Either way, unless a user manually downloads the xml until it is fixed it is not possible to use the plugin manager.

**Comment by chcg** [comment]
@CollinChaffin There is an issue with the TLS certificate of the dev list. The normal list is not affected as far as I see. This could just be fixed by Dave.

**Comment by bruderstein** [comment]
That's not what the md5 does. I think this is the certificate error. The md5 is just used to see if it should download the list again (manual caching from the days when we couldn't control e-tags and cache headers)

I've had one go at the certificate and ran out of time. For now, use the production list.

**Comment by CollinChaffin** [comment]
Will do.  Wasn't sure if you were aware of it as many of us regularly use the dev plugins but will change to stable I guess as a temp workaround until you get it sorted.  Might want to keep this issue open though so others using dev list are aware because as I indicated (and you've now corrected me again) the plugmgr simply breaks when set to dev, and it simply indicates a general connectivity error and no indication to the user that the stable list is a viable working option without coming here for that answer.

**Comment by chcg** [comment]
@CollinChaffin  Seems to be fixed. Could you confirm that.

**Comment by chcg** [comment]
@bruderstein Certificate for the website has timed out yesterday again. Seems this one is not affected. Could we close this task?

**Comment by chcg** [comment]
@bruderstein Thanks for certificate update.

**Comment by chcg** [comment]
Now all the lists are fine again. 32/64 bit for normal and dev
