### ISSUE TITLE
Include Stirlitz in manager

### ISSUE THREAD

**Issue by dragokas** [bruderstein/nppPluginManager#135]
Hi,

I'm using Stirlitz for N++ for several years. It has a good stability.
Can you please add it to your manager?

Info (author): https://vk.com/wall203102356_293
Download link: https://yadi.sk/d/NWpQGao7FAzJB

Thank you.

**Comment by chcg** [comment]
@dragokas Could you please check data from https://npppm.bruderste.in/plugins/view/stirlitz

Added:
```

The Shtirlitz plug-in menu lists decoding styles. Choose a style - and this style decodes the selected text (Turbo-5 style should fit in most cases). The styles themselves and all the settings can be made by Stirlitz.exe, which is in the Shtirlitz folder. He is there without advertising pictures and due to this only 428 KB.
Latest updates

[2014-01-03]

Stability: Good

Author: Vsevolod Lukyanin

Homepage: https://vk.com/wall203102356_293
Unicode Install

Latest version: 1.0

    Download https://downloader.disk.yandex.ru/disk/e691222ed300dbc2add596e3319c83be4097215edf70a6285b647314c41221d5/5bf944f2/WLty9M9M5it9ro2gTQmO-XjOrsPk2UaC5XsYsMIVVw55o-ZDAWsak5eLfZ4oR5egDBHdy7evXp_JSCChDWLqPQ%3D%3D?uid=0&filename=shtirlitz_plugin.zip&disposition=attachment&hash=Q5sj6S9p5uKqNYbv9V%2BTScC2GO9Q49A0fLjOFybeXlw%3D&limit=0&content_type=application%2Fx-zip-compressed&fsize=343203&hid=a1f60621a9dadef9e2770edfd39078c3&media_type=compressed&tknv=v2 MD5: 1d9f2f274c8c6f39eb2bf56e3dc34a4d
    Copy from: ShtirlitzNppPlugin.dll To: $PLUGINDIR$\ Validate Directory
    Copy from: Shtirlitz\*.* To: $PLUGINDIR$\Shtirlitz Validate Directory

Unicode Uninstall

    Delete $PLUGINDIR$\Shtirlitz


```

**Comment by dragokas** [comment]
Hi,
thank you.

https://npppm.bruderste.in requires registration. I can't register, because I don't receive confirmation email.
Also bruderste.in certificate has expired. It was valid until November 22, 2018.
When I click "Use development plugin list", plugins list is empty. Usure, is it correct. According to the description, this item is exactly intended for preliminary testing.

**Comment by dragokas** [comment]
Information you provided in quoted part above is correct.
However, I'm unsure about download link. You can't build universal direct download link to disk.yandex.ru
I hope you'll upload the plugin somewhere on your FTP.
And yes, there is no x64 version of this plugin.

**Comment by chcg** [comment]
@dragokas PM 32bit DevList is working again.
As you said the download is not possible as the link is not stable.
Could you contact the author to provide it somewhere easier accessible, maybe even the as github project. What about the copyrights for the contained exe?

**Comment by dragokas** [comment]
Hi, chcg!

I asked the author, Всеволод Лукьянин, to publish his plugin on GitHub and he agreed to do so:
https://github.com/shtirlitz-dev/notepadpp-plugin/tree/master/unzipped

Please, note that dll requres 2 files in subfolder:
 - Shtirlitz\Shtirlitz.cfg
 - Shtirlitz\Shtirlitz.dat

exe-file is not needed. As about copyrights for that exe. They are the same. Author is Всеволод Лукьянин.

Regards,
Stanislav.

**Comment by dragokas** [comment]
> 
> 
> @dragokas PM 32bit DevList is working again.

DevList is working, but usual list is now become broken!
Uncheck mark "dev. list" and you will see "no plugins available".

**Comment by chcg** [comment]
@dragokas Updated the download link with the github zip.

**Comment by dragokas** [comment]
Thank you. It install correctly.

But you don't understood. I mean, currently no plugin is displayed in list when "dev list" unchecked.

**Comment by chcg** [comment]
I saw it, but can't fix it. Just @bruderstein could do that. The zip file downloaded from the server which should contain the plugin list is corrupt and just contains some error texts instead of the xml. Typically there is a sync between the dev list and the productive list each two weeks. So hopefully with the next sync this gets corrected automatically if dave doesn't have a look at that in the meantime.

**Comment by chcg** [comment]
@dragokas pluginlist is now working again and x86 plugin is part of it.

**Comment by dragokas** [comment]
Plugin list is really working.
But, Shtirlitz is now disappeared from both lists at all !!!

**Comment by dragokas** [comment]
Hi, @chcg.

After several years, Shtirlitz author made update and provide 64-bit version !!!
Also, 32-bit version is now one portable dll and it has new location.

Please, correct paths in manager:
32-bit: https://github.com/shtirlitz-dev/notepadpp-plugin/blob/master/32bit/ShtirlitzNppPlugin.dll?raw=true
64-bit: https://github.com/shtirlitz-dev/notepadpp-plugin/blob/master/64bit/ShtirlitzNppPlugin.dll?raw=true

**Comment by chcg** [comment]
@dragokas See https://github.com/shtirlitz-dev/notepadpp-plugin/issues/1 a zipped version of the dll is needed.

**Comment by dragokas** [comment]
Zip-version of each dll?
Or zip-version of both dll in one archive?

**Comment by chcg** [comment]
@dragokas Each dll in a own zip.

**Comment by dragokas** [comment]
hi, here are zipped versions:
32-bit: https://github.com/shtirlitz-dev/notepadpp-plugin/blob/master/32bit/ShtirlitzNppPlugin.zip?raw=true
64-bit: https://github.com/shtirlitz-dev/notepadpp-plugin/blob/master/64bit/ShtirlitzNppPlugin.zip?raw=true

thanks.

**Comment by chcg** [comment]
Added to PluginManager and PluginAdmin for 32\64bit.
