### ISSUE TITLE
Plugin Manager begins downloading list and crashes

### ISSUE THREAD

**Issue by JayRTurner99** [bruderstein/nppPluginManager#138]
### Description of the Issue
Notepad++ said that Plugin Manager and JSONViewer had updates. Updating requested to update Plugin Manager first. I updated Plugin Manager. requested was updated to version 

### Analysis
See Debugging information below to note that CSScriptNpp.dll could not be found because it is referring to 'file:///C:\Program Files\Notepad++\plugins\CSScriptNpp\CSScriptNpp\CSScriptNpp.dll' but should refer to 'file:///C:\Program Files\Notepad++\plugins\CSScriptNpp\CSScriptNpp.dll'.

There is a CSScriptNpp.64.dll file (v1.7.8.0 via Windows Properties) and providing the CSScriptNpp.dll file (v1.7.8.0) causes Notepad++ to start and declare that it "Cannot load 32-bit plugin" and that "CSScriptNpp.dll is not compatible with the current version of Notepad++"

### Components
Notepad++ v7.5.9 (64-bit)
HTML Tag v1.1.0.0
Converter v4.2
DSpellCheck v1.4.6.0
JSON View v1.31
MIME Tools v2.1
Plugin Manager v1.4.12.0 (from Windows Properties for PluginManager.dll)
XML Tools v2.4.9.2 unicode; libXML 2.9.3, libXSTL 1.1.28

### Steps to Reproduce the Issue

1. Open Notepad++
2. Click Plugins > Plugin Manager > Show Plugin Manager
3. Plugin Manager dialog opens and displays "Downloading plugin list..."
4. Wait 5 seconds
5. Notepad++ : a free (GNU) source code editor has stopped working

### Expected Behavior
I expected Plugin Manager to load the current list of plugins.

### Actual Behavior
Notepad++ has stopped working

### Debug Information
Notepad++ Debug Information:
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll HTMLTag.dll NPPJSONViewer.dll PluginManager.dll XMLTools.dll 

Plugin Manager Debug Information:
Cannot be obtained because the Plugin Manager crashes the application.

Visual Studio 2017 Debug Information:
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Kbg.NppPluginNET.UnmanagedExports' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'file:///C:\Program Files\Notepad++\plugins\CSScriptNpp\CSScriptNpp\CSScriptNpp.dll' or one of its dependencies. The system cannot find the file specified.

**Comment by chcg** [comment]
See e.g. https://github.com/oleg-shilo/cs-script.npp/issues/28. The modifications of N++ in preparation for the builtin PluginAdmin with 7.6 (https://notepad-plus-plus.org/news/notepad-7.6-released.html) caused some trouble for existing plugins. https://github.com/oleg-shilo/cs-script.npp/releases/tag/v1.7.24 should fix the problems.

Be aware that PM just works up to N++ 7.5.9 and not really with 7.6 apart from displaying the plugin list.
