### ISSUE TITLE
Crash when reading update release note 

### ISSUE THREAD

**Issue by cmeriaux** [bruderstein/nppPluginManager#14]
today, when I started up Npp, plugin manager asked me to update Python Plugin (do you know this plugin ? I’m joking)
While I was reading the release note, Notepad++ crashed. Here is the stack dump from VS and debug info. Sorry I don’t have the sources or debug symbol.

Bug reproduced twice, Here is the step to do

Edit the PluginManager.ini, set LastCheck to 0, to force the plugin check
Open Npp,
wait while plugin Manager windows is not open.
Once plugin Manager windows is open, you can continue to use Npp, the program is stable.
Now click, on Plugin Manager Windows on the Python Script, Npp is still stable and waiting. I can go back to Npp windows, all is stable.
Now click on the Plugin Manager / text area of the release note.
Bang ! Core Dump.

Do you confirm ?
Christophe

**Comment by bruderstein** [comment]
Great, thanks for the report. Yes, reproducible. I'll fix it and release again before we release proper.

Thanks for reporting!

**Comment by bruderstein** [comment]
Fixed in a5b1135. Release v1.4.2 - thanks again for reporting with great repro steps!

**Comment by cmeriaux** [comment]
it was a pleasure.
