### ISSUE TITLE
Error downloading the plugin list

### ISSUE THREAD

**Issue by btrower** [bruderstein/nppPluginManager#148]
This is similar to a closed issue here: 
https://github.com/bruderstein/nppPluginManager/issues/57

This happened to me just now for the first time. There is more than one problem with this:

1) There is nothing wrong with the network at my end, so the error message is wrong.
2) Local software should never stop working because it can't reach the network.
3) Applications should not put up application modal windows unless (literally) the next keystroke would cause unrecoverable damage. In the case of ordinary usage such as (in my case) just opening the app, that means never because it should not start up in a state capable of breaking anything.

The app modal message box on my screen is the second one I had to negotiate just opening the program to edit a file locally. It is literally stopping me mid-keystroke twice for nothing.

I have been programming for more than forty years and I am quite, quite clear about points 1, 2, and 3. Don't, don't, don't.

For the past year, at least I, I have periodically had notepad++ lock up on me so that I had to kill the process with Task Manager. I am not sure that it's a modality problem in that case, but it is similar to the application opening a modal window behind itself so that I can't dismiss it.

Notepad++ has been my go-to editor for years and it will continue to be, but it is annoying as hell that every few times I open it up I have to kill the process and restart, or am stopped cold by a modal window asking me if I want to update. I touch type and I really just want to get editing when I open this application. What were people thinking when they put in something that routinely disables the software until the user attends to something minor and even irrelevant?

Please, anybody who is working on this, find a way to make it so the software does everything it can to do its job as an editor. Just the job. If you have what you consider vital text you just can't stop yourself from displaying put up a red tab on the tab bar so I can at least ignore it while I get on with the task. Microsoft, with its crazy festival of bugs that put errors in the event log, advises users to ignore those errors. They won't ever fix them, but at least they don't actively interfere with your work. Let me at least do that.

**Comment by chcg** [comment]
@btrower Are you still using a N++ version before 7.6.x? Otherwise you should change and use the built-in PluginAdmin. See https://github.com/bruderstein/nppPluginManager/issues/139 and https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.12. I will update to readme to state that this project is abandoned in favour of the built-in plugin management of N++.

**Comment by btrower** [comment]
@cncg -- Thanks for the gracious reply. Next time I see that particular error, I will update Notepad++ in that place. 
I use or maintain a lot of different user machines and VMs. That's part of the reason my subjective experience is basically that every second or third time I use notepad++ it won't let me until I attend to one thing or another. I looked around and found a version that was below 7.6 (7.5.9) on a laptop i only use at particular times, but that is not the machine that lead to the issue. Except that it stopped me to inform me of an update, it did not have the issue that is the subject of this defect report. I'll update it now. 
Knowing what in particular I have to fix is a 'good to know'. At least I don't have to wonder, but as a practical matter, it is not manageable as a solution to the problem generally. 
Since the inception of Notepad++, numerous additional applications have appeared and the ecosystem is becoming unusable because every app developer is acting as if their application is the only one anybody is using and that users somehow should spend a part of every day attending to maintenance of their applications. 
The iPhone store has more than a million apps. I use as few apps on my iPhone as I can, but some can't be avoided. I devote my time and bandwidth updating those apps every week or two, but I just checked and twenty-two apps have pending updates. Unbelievably some of these app creators have their apps refuse to work until they are updated. As a user, that is a part of the environment within which I am using Notepad++. Only so many apps can demand attention before nothing at all can be used due to the constant requirement for updates. Microsoft cheerfully disables Windows machines for hours and even days for updates, so there is often not a lot of time left to deal with other stuff. 
Just as a matter of ethical community hygiene, developers should be limiting updates to benign background updates that can roll themselves back and even then only when it is truly important to do so. If nothing else, you should do a rock-solid version that remains feature stable and backward compatible for years. This is an editor. It can and should edit without interruption or complaint every single time it is invoked. It can be months between times I work on *NIX systems and some particular systems I might not see for literally years or more. When I want to edit a file, I type 'vi [filename]' and return and I am editing. In the more than thirty five years I have been using it, the subset I used has not changed and it is rock solid. Once you have learned to use an editor, you should *never* have to attend to anything besides editing and getting on with your work. Imagine if every single time you picked up a hammer you had to go fetch a novel head, figure out how to attach it and spend a few minutes learning a new way to hammer. I should be attending to my fingers, the nail and the thing that it is going into, not the hammer. In the universe of text editing, something like Notepad++ is a hammer. It should work and work the same every time. 
I am responsible for other code-bases and projects, so I can't set up a build environment, download and build and familiarize myself with the code base, figure out how to properly make a change and then work with incumbents to get the code into production. If it is exceedingly difficult for some reason to fix these issues, I guess we will have to live with them, but if you (whoever is in the code) can possibly do so, try to find some way that you only ever halt the program and demand user input when to do otherwise would cause unrecoverable damage. As I implied before, a program just starting up should not be calling a 'halt and catch fire' instruction anywhere, so in practice such an interruption should simply never happen. 
Again, thanks for your reply. I know there are a million things to attend to and things can get away from you, so I will let this be. 
Cheers!

**Comment by chcg** [comment]
@btrower For N++ there is an option to suppress updates and the corresponding question/window. Also PluginManager has an option to avoid the updates/notification:

![grafik](https://user-images.githubusercontent.com/12630740/87252538-36a11c00-c474-11ea-8b67-2ec4fdd2daa1.png)

**Comment by btrower** [comment]
@chcg Thanks. 
Plugin Manager was not part of my Notepad++ installation. I tracked down what I hope is a good version (V 1.4.12) and installed on the machine I am currently using by creating a new directory:
C:\Program Files\Notepad++\plugins\PluginManager\
and copying PluginManager.dll into it. 
This is hardly intuitive and I cannot imagine how a naive user could possibly figure this out and do it in a reasonable amount of time. 
Anyway, I have done that and have unchecked the notify box. It seems unlikely to me that this will stop the program itself from stopping to inform me of a program update, but I am hopeful. :)
