### ISSUE TITLE
Plugin list (PluginManagerPlugins.xml) is not up-to-date

### ISSUE THREAD

**Issue by DmitrySokolov** [bruderstein/nppPluginManager#2]
PluginManagerPlugins.xml downloaded by PluginManager is not up-to-date.
Some plugins have updated already but PluginManagerPlugins.xml keeps old versions.

**Comment by oleg-shilo** [comment]
Second it. 
Currently a 9 month old version of CS-Script plugin is distributed even though it was superseded with the next one submitted (via http://www.brotherstone.co.uk/npp/pm/admin/plugins) 8 month ago.

What is even more strange is that I am almost 100% sure that at some stage PluginManager was delivering the ~4 month old plugin version but now went "back in time" to the 9 month old one.

**Comment by bruderstein** [comment]
Updated.
