### ISSUE TITLE
Not saving PluginManagerPlugins.xml in correct location for portable version

### ISSUE THREAD

**Issue by Gitoffthelawn** [bruderstein/nppPluginManager#20]
Hi Dave.  Thank you for the Plugin Manager.

For portable Notepad++, nppPluginManager v1.4.3.0 is not saving `PluginManagerPlugins.xml` in the correct location.

It is saving it in `[notepad++ folder]\plugins\Config\data\prod\content\xml`, but in order to recognize that file, it must be saved in `[notepad++ folder]\plugins\Config\`.

This may be due to an issue in the Plugin Manager, or simply that `PluginManagerPlugins.zip` currently contains `PluginManagerPlugins.xml` within `data\prod\content\xml` inside the zip file.

As a workaround, the user can copy `PluginManagerPlugins.xml` to `[notepad++ folder]\plugins\Config\`, but they will need to do that every time a new version of `PluginManagerPlugins.zip` is released.

**Comment by bruderstein** [comment]
Thank you so much for reporting this - there was an issue with the zip file stored on the server. This has now been rectified. Restarting Notepad++ and opening the plugin manager will redownload the file (it may be cached by your browser cache for a few hours)

**Comment by Gitoffthelawn** [comment]
You're welcome.  Glad to help.
