### ISSUE TITLE
Link to nowhere

### ISSUE THREAD

**Issue by Gitoffthelawn** [bruderstein/nppPluginManager#21]
Plugin Manager v1.4.3.0 includes a link entitled *Why is this here?*.  That link goes to http://bruderste.in/npp/pm/sponsor/ which currently generates a 404.

**Comment by bruderstein** [comment]
Fixed! Thanks for reporting!

**Comment by Gitoffthelawn** [comment]
You're welcome!  Thanks for the Plugin Manager!

**Comment by cmeriaux** [comment]
The HTML pages is available but there is a typo at the beginning of the 1st paragraph : 
TL;DR: 
It's just a detail. Sorry

**Comment by Gitoffthelawn** [comment]
To confirm, http://bruderste.in/npp/pm/sponsor/ now responds with the proper content instead of a 404. :-)
