### ISSUE TITLE
The plugin manager does not work with npp 64bit

### ISSUE THREAD

**Issue by yquoulali** [bruderstein/nppPluginManager#27]
Hello,

I have installed the last 64bit version of npp (7.2.1). But the plugin manager is not showing on the Plugins menue, so i installed it manually (version 1.4.3), after restart, i got a message that 32bit plugins couldn't be loaded.

Is there is a 64bit release, or should we build it from the source manually ?

Thank you.
Best regards.

**Comment by chcg** [comment]
See #7, there is currently the x64 branch for that work. No release so far.

**Comment by bruderstein** [comment]
Closing as duplicate / already tracked. (@chcg feel free to close issues!)
