### ISSUE TITLE
Does it support socks5 proxy?

### ISSUE THREAD

**Issue by rexdf** [bruderstein/nppPluginManager#30]
Connection to many sites such as sourceforge.net and github.com in China are interrupted now and then.

**Comment by chcg** [comment]
@rexdf See https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html, since version 1.2.0:

Downloads now using WinInet API instead of <a href="http://curl.haxx.se/libcurl/">libcurl</a>. Hence now using system proxy (same as IE and Chrome), and smaller binaries.
Better UAC support. If you start Notepad++ as a normal user, then install something, N++ will be restarted as the same user (not as admin as per previous versions)

Is this sufficient for you?

**Comment by rexdf** [comment]
Most of package manager such as **apt/yum** , **python pip**, **node npm** , or **git/svn/hg** have a builtin proxy or mirrors support. Chrome has entension such as `Proxy SwitchyOmega`. I would prefer a proxy for every single programming rather than a gloabl proxy.

**Comment by bruderstein** [comment]
Supporting proxies internally is a large amount of work (& code to maintain). As @chcg said, we used to have proxies supported under libcurl, but we couldn't support all types of proxies (specifically NTLM authenticated "corporate" proxies and automatically configured proxies), and having to set the proxy up again was irritating for many users.  It also meant keeping the passwords only in a semi-encrypted state, which was obviously very bad for security. 

Using the built in proxy is simpler for the vast majority of users, and gives us support for all proxy types and setups, and allows passwords to be managed and encrypted by the OS.

If you'd like to submit a PR with all this support natively baked in, (and are willing to maintain it), then send it in!

**Comment by rexdf** [comment]
@bruderstein  I'd  like to make it support some kind of proxy.  My proxy is  something like 127.0.0.1:1080  (socks5 http or https) and there is no password.

But I am not familiar with C++.  What if we read a configure like 

```
[Settings]
...
ProxyEnable=1
Proxy=http://127.0.0.1:1080
```

if `ProxyEnable=1` then change following line 

https://github.com/bruderstein/nppPluginManager/blob/master/libinstall/src/InternetDownload.cpp#L20

to

```
m_hInternet = ::InternetOpen(userAgent.c_str(), INTERNET_OPEN_TYPE_PROXY, s_Proxy /* proxy*/ , TEXT("<-loopback>") /* proxy bypass */, INTERNET_FLAG_ASYNC /* dwflags */);
```

**Comment by bruderstein** [comment]
It already supports all the proxy types. Just set it in chrome or internet
explorer/edge, and it works. There is no reason to add this (there doesn't
seem to be any legitimate reason to want a different proxy for web browsing
as downloading plugins)

**Comment by rexdf** [comment]
@bruderstein For example, I am watching  video or doing on-line shopping and paying for my location in Internet or Edge. At the same time, I open a small bin file in n++ and edit it.  I don't need a system proxy to interrupte my work.  The online-shopping system recommand commodities according to IP address and the video is copyright only to be played in my location.

**Comment by rexdf** [comment]
There is no need to support global proxy at all, and all modern operating systems support VPN in your opinion.

**Comment by bruderstein** [comment]
I am not prepared to support a proxy local only to this plugin. Almost all users either have a proxy they use to connect to internet, or not, and do not have different proxies for different things. This is why the proxy is shared between chrome and internet explorer, for example (it used to be separate).
It also means proxies authenticated by the OS can be supported, by using the OS calls.  If you want to support this for your use case, then you'll need to either fork or submit a PR and be prepared to support it. The simple case above would break support for many many users.

Closing this issue to further comments - sorry, my time is limited.
