### ISSUE TITLE
Creating plugin repository mirror

### ISSUE THREAD

**Issue by yaruson** [bruderstein/nppPluginManager#31]
Is it possible to create a mirror of nppPluginmanager's database and plugin repository? Internet connection isn't available to me, but I can create intranet copy of any resource.

**Comment by bruderstein** [comment]
This should be possible, but you'd have to fix the DNS name - if you can override that, then it should be straightforward.

You need to serve a zip file containing a single file "PluginManagerPlugins.zip" from https://nppxml.bruderste.in/pm/xml/plugins.zip

You can make it http if you set an option in the pluginmanager.ini (I can't remember off hand, something like forceXmlHttp=1 - search this repo)

The plugins themselves come from various locations, depending on the plugin author's preference. Some are github releases, some sourceforge, some on their own site. I don't think there's an easy way of mirroring all of those. You could, if you were interested enough, go through the xml, alter the URL in each download step, and mirror the files locally. That's a lot of effort though.

**Comment by yaruson** [comment]
Thank you for the explantation. I managed to download all (almost, there're some 404s) files from XML and replace with links to local web server.

Is there some easy way to make plugin access custom URL and not default https://nppxml.bruderste.in/pm/xml/plugins.zip?

**Comment by bruderstein** [comment]
Thought I'd replied to this already.

Not easy - deliberately. The security issues around allowing this change at the user issue were too great. You'd have to build a new version with the URL you want to use. If you take the current master branch, it's a lot easier to build - @chcg has done some great work making building easier.

**Comment by chcg** [comment]
Check appveyor.yml for automatic CI builds, which is also possible for a forked version after registration at appveyor. Currently #28 is not merged yet.

For local builds adapt path.props.sample and rename to path.props and load VS solution.

**Comment by bruderstein** [comment]
Closing this as I think we've answered everything possible here.
