### ISSUE TITLE
Feature Request: UDL repository

### ISSUE THREAD

**Issue by chcg** [bruderstein/nppPluginManager#33]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1286

It is not good to write UDLs into wiki and install them manually.
Could you create a new repo for UDL and add the code into NPP Plugin Manager to manage UDL's

**Comment by bruderstein** [comment]
Oh, user defined languages! That took me a moment. Great suggestion, and something plugin manager could definitely take care of.

**Comment by chcg** [comment]
Another candidate:
https://notepad-plus-plus.org/community/topic/13371/udl-for-stan-statistical-modelling

**Comment by rddim** [comment]
I want this too. I have created an UDL for AutoCAD `*.lin`,` *.scr`, `*.shp`, and `*.pat` files. It contain also Auto-Completion files for Notepad++ function. The repo is [here](https://github.com/rddim/notepad-plus-plus-autocad)

**Comment by chcg** [comment]
@rddim Added https://npppm.bruderste.in/plugins/view/udl-autocad for testing with:

> 
> Author: Rusi Dimitrov
> 
> Homepage: https://github.com/rddim/notepad-plus-plus-autocad
> Unicode Install
> 
> Latest version: 2.0
> 
>     Download https://github.com/rddim/notepad-plus-plus-autocad/releases/download/v2.0/NPP_AutoCAD_v2.0.zip MD5: fd587da105ecf330bea919e425840b43
>     Copy from: plugins\APIs\*.xml To: $PLUGINDIR$\APIs Validate Directory
>     Copy from: userDefineLang\*.xml To: $PLUGINDIR$\UDL Validate Directory
> 
> Unicode Uninstall
> 
>     Delete $PLUGINDIR$\UDL\ACAD-Linetype.xml
>     Delete $PLUGINDIR$\UDL\ACAD-Script.xml
>     Delete $PLUGINDIR$\UDL\ACAD-Shape-Hatch.xml
>     Delete $PLUGINDIR$\APIs\acad-linetype.xml
>     Delete $PLUGINDIR$\APIs\acad-script.xml

Autocompletion could be added flawlessly, but UDL is a problem as the import couldn't be done without support of either N++ or adding some own code to modify userDefineLang.xml.

Additionally there is no possibility to check the currently installed version.

**Comment by rddim** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/dfb9b5e330c2fe3dcfea436f969e213f001ece05

**Comment by rddim** [comment]
Hello, the repo https://github.com/rddim/notepad-plus-plus-autocad is no longer maintained and I think to delete it after 6 months. I have created a new one here https://github.com/rddim/npp-udl with the new folder structure for Notepad++. It contain two UDLs at now.

**Comment by chcg** [comment]
Adapted for x86 at https://npppm.bruderste.in/plugins/view/udl-autocad to use release 19.1 of autocad.

**Comment by chcg** [comment]
So with N++ 7.6.4 plugin manager would be able to support UDLs and AutoCompletion delivery\installation within the existing plugin workflow also the GUI has no extra tab for them and they could be just found be naming conventions right now. As PluginManager is no longer actively developed and just supports plugins correctly for N++ < 7.5.9 I will close this issue.
It is still possible to add UDLs to the existing plugin list and changes therefore will be accepted.
