### ISSUE TITLE
Plugin manager prints "destructing 4" to console

### ISSUE THREAD

**Issue by Pokechu22** [bruderstein/nppPluginManager#34]
### Description of the Issue
When closing the plugin manager, the following is printed to the console:

> ```
> destructing 4
> destructing 3
> destructing 4
> destructing 3
> destructing 2
> destructing 1
> ```

These messages should not be printed, since they seem to be a leftover debug string and have no actual relevance to the user (although, the fact that `destructing 4` is printed twice is a bit worrisome).

### Steps to Reproduce the Issue

1. Start Notepad++ with a console attached.
    
    This is _probably_ the most difficult step.  The majority of the time, the console refuses to appear or to stay open.  However, it _does_ open when Notepad++ is launched through [Cygwin](http://cygwin.com/), such as [for use as a git commit message editor](http://stackoverflow.com/a/1635493/3991344).  No special flags are _actually_ needed; simply running `notepad++.exe` from bash makes it visible.

    Alternatively, if Cygwin is not an option, simply adding a call to `AllocConsole()` is enough to get the console to appear when debugging from visual studio.  Of course, in this situation, the console has to manually be opened; you wouldn't run into the issue that way from normal usage.
2. Open the plugin manager.
3. Close Notepad++ (Cygwin only &mdash; seems to be necessary to get the output to be flushed)

### Expected Behavior

The console to remain blank.

### Actual Behavior

The following is printed to the console:

> ```
> destructing 4
> destructing 3
> destructing 4
> destructing 3
> destructing 2
> destructing 1
> ```

### Debug Information

<h4>Regular install</h4>

```Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Users\Pokechu22\Downloads\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll
```

<h4>From visual studio</h4>

```Notepad++ v7.3.1   (32-bit)
Build time : Jan 31 2017 - 21:46:54
Path : C:\Users\Pokechu22\Downloads\notepad-plus-plus\PowerEditor\visual.net\Unicode Debug\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll
```

### Cause

[Line 31 of `CancelToken.cpp`](https://github.com/bruderstein/nppPluginManager/blob/886e4fc2a4f0a157eaf0378da1f9301b320d0cdd/libinstall/src/CancelToken.cpp#L31) contains:

```cpp
printf("destructing %d\n", *m_refCount);
```

Removing that line should fix the issue.

**Comment by chcg** [comment]
Maybe OutputDebugString() might be better here. I think it is no bug that the refcount is shrinking and expanding again on shutdown. This depends on the referenced objects existing at that time.

@Pokechu22  Do you see any real issues with this behaviour? Anything not working? Or is this just an annoying output.

@bruderstein Any idea why this was added? There is just one version of CancelToken.cpp and the printf is already contained in that version. Seems to be there just for debugging purposes to me.

**Comment by Pokechu22** [comment]
> Do you see any real issues with this behaviour? Anything not working?

I see no issues with the count increasing and decreasing; the only reason it concerns me is because the [post I found when searching for it](http://stackoverflow.com/questions/38118886/git-pull-shows-destructing-messages) had a strictly decreasing counter.  It's entirely reasonable for it to increase and decrease or it not to, but since it's different from the way it seemed to behave in the past (from that one issue), it felt like something that _could_ be a bug.

> Or is this just an annoying output.

More or less; it's just that when it combines with other messages ([as in the same SO post](http://stackoverflow.com/questions/38118886/git-pull-shows-destructing-messages)) it can be really confusing.

**Comment by chcg** [comment]
@Pokechu22 See http://www.linuxprogrammingblog.com/cpp-objects-reference-counting on reference counters. Ok, I see. But that just happens if you open the plugin manager, not just on opening and closing N++, or?

**Comment by Pokechu22** [comment]
> But that just happens if you open the plugin manager, not just on opening and closing N++, or?

It only happens if you open the plugin manager, and only happens once upon opening the plugin manager.  I guess some videos may make it clearer; I can't attach individual video files but [here's a zip of them](https://github.com/bruderstein/nppPluginManager/files/746571/nppVideosFor34.zip).

* `n++ cygwin git commit.mp4` shows the effect this has on git commit.  It only occurs when the plugin manager is opened; this is actually what makes it confusing.
* `n++ cygwin open and closed.mp4` shows opening and closing Notepad++ in Cygwin without opening the plugin manager.
* `n++ cygwin open plugin manager once.mp4` shows opening the plugin manager in Cygwin once, and then closing Notepad++.  This is where the output occurs.
* `n++ cygwin open plugin manager twice.mp4` is the same as the above, but opening the plugin manager twice (showing the output only occurs once).
* `n++ visual studio.mp4` shows what the output looks like in visual studio with a call to `AllocConsole()`; this is useful because it shows when the log output happens in real time (unlike with Cygwin).

**Comment by bruderstein** [comment]
I think it was just there when I created it to aid in debugging, and ensuring that the right steps happened in the right order. I don't see any issue, just this extra `printf`. I'll remove it.

**Comment by chcg** [comment]
@bruderstein Could you check the last merge of mine. You wanna do it locally. Then I could also do this one for you. Nice to see you back.

**Comment by bruderstein** [comment]
@chcg - we were going to rebase that merge werent't we - I'll do it now.

**Comment by chcg** [comment]
ok. 

Think  #28 is the open one, maybe you could have a look, think the deployment question (vs120_xp or vs140_xp) is still open. You could have a look at https://github.com/pnedev/compare-plugin/blob/master/appveyor.yml how it could look like and work.
The PR itself needs a cleanup and I will create a new one with the necessary adaptions.

**Comment by chcg** [comment]
Removal of the printf done with 0c6ed2c

**Comment by Pokechu22** [comment]
Thanks!

**Comment by Pokechu22** [comment]
I just had this happen again.  (I know that the fix hasn't peen put into a released build, though, so that's not unexpected).  However, what's interesting is that I didn't open the plugin manager; I'm completely sure of that.  Is it possible that the automatic update check (that by default happens every 14 days) could also cause this to occur?

**Comment by chcg** [comment]
Fix contained in https://github.com/ashkulz/NppFTP/releases/tag/v0.26.8
