### ISSUE TITLE
I built it use appveyor for master branch, but plugin list is empty.

### ISSUE THREAD

**Issue by dreamchen** [bruderstein/nppPluginManager#39]
I built it use appveyor for master branch.
the tag [1.4.4_beta](https://github.com/dreamchen/nppPluginManager/releases/tag/v1.4.4_beta) was support x64
The 1.4.4_beta is work on Win10 x64,but the plugin list is empty.
I use the capture tool find server IP is 104.18.50.38, this IP can be ping.

**Comment by chcg** [comment]
Expected behaviour as the server side is not prepared for x64 yet. This is work in progress. See https://github.com/bruderstein/npppm3

**Comment by dreamchen** [comment]
Okay, I know. Is there an expected completion time?

**Comment by bruderstein** [comment]
No.

I hope to have the site in a publishable state in a week or so, then people can help with the remaining tasks to get it live.

**Comment by chcg** [comment]
Please use #7 for further discussion
