### ISSUE TITLE
Notepad++  Crashing instantly when tries to open

### ISSUE THREAD

**Issue by puneetgupta22** [bruderstein/nppPluginManager#4]
My Notepad++ suddenly starts creashing when i try to open.
I tried it with Run as Administration, but again it is not working correctly.

Should I delete my PluginManager.dll file?

Gettling Below Error Message
Problem signature:
  Problem Event Name:	BEX
  Application Name:	notepad++.exe
  Application Version:	6.9.2.0
  Application Timestamp:	573b9c9e
  Fault Module Name:	PluginManager.dll
  Fault Module Version:	1.3.5.0
  Fault Module Timestamp:	54bbbb11
  Exception Offset:	0002e6e3
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	16393
  Additional Information 1:	f76b
  Additional Information 2:	f76b2652c8941daea9d6a129b3996b47
  Additional Information 3:	0d75
  Additional Information 4:	0d7510ec42adeb6f01d6d815497307b7

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by bruderstein** [comment]
Delete the PluginManagerPlugins.xml, and rename PluginManagerGpup.xml to PluginManagerGpup.backup.xml if it exists from the config directory, then try starting notepad++ again.

The config directory is usually in %APPDATA%\notepad++\plugins\config

It would be great if you could post the contents of PluginManagerGpup.xml (which I why I suggested renaming it - it's safe to delete otherwise) if that fixes it.

**Comment by puneetgupta22** [comment]
Hi Bruderstein,

I have a file named as '**PluginManager.dll**' [_Path:Program Files (x86)\Notepad++\plugins\PluginManager.dll_] in , I simply remove it from there.
After that my Notepad++ is working fine.

========================

I checked the file mentioned by you **PluginManagerPlugins** [_Path:  \AppData\Roaming\Notepad++\plugins\config\PluginManagerPlugins.xml_] but didn't take any action on it and also there is no file with name '**_PluginManagerGpup.xml_**' at the same path.
Attaching the snapshot of same: http://image.prntscr.com/image/d5d118b693b04fe5a027ed1a0db6888a.png

**Comment by bruderstein** [comment]
Closing this as nothing really further - we don't know what caused it. :(
