### ISSUE TITLE
Plugin Validation failure

### ISSUE THREAD

**Issue by pnedev** [bruderstein/nppPluginManager#41]
Hello @bruderstein ,

Thank you for the great plugin - it really makes N++ look complete and much more user-friendly.

I recently released a new version of an existing plugin and selected "Validate" in the install form. I let the site compute the Md5 sum itself from the new version link and when the list of the plugin files in the zip appeared I added the hashes ("Add hash") for every file existent. I saved the modifications made to the plugin xml.
The problem is that when I try to install the new version from PluginManager the files give validation errors (as if the hashes mismatch).
My PluginManager is the latest version (1.4.3) and I have enabled the use of the development xml list (so my plugins xml changes are immediately active).
Could you please check if the hashes are correctly computed, saved in the plugins xml list and validated correctly?
Thank you in advance.

BR

**Comment by chcg** [comment]
Hi,

just tested a new installation of Compare 2.0.0 on Win10, n++ 7.3.2, PM 1.4.3 and that didn't show the hashing issue with the dev list. The actual commonly used list shows this issue.

**Comment by bruderstein** [comment]
It does take a few minutes before the dev list is updated. The prod list has just been updated - so this should be live now.

However, the same file hash has been there a while (2016-12-19 was the first time it was added).

I'll check I can install it when I get to a windows machine.

**Comment by pnedev** [comment]
Hello @chcg ,

Yes, I have disabled my plugins validation in the dev list due to the issue I mention. The normal list still has the validation on and fails the hash checks. Thanks for testing.

Hello @bruderstein ,

> It does take a few minutes before the dev list is updated.

Hm, that might be causing the problem I observe. I tried adding the hashes and then immediately used PM (with the dev list) to check the validation is passing but it is failing. Perhaps I need to wait half an hour before testing in order for the dev list to actually get updated.
Thank for helping.

BR

**Comment by pnedev** [comment]
Hello @bruderstein ,

One update:
The problem is not caused by the dev list being updated with delay - I enabled the Validation again + adding the hashes (it was reported the hashes were already there BTW) and waited a day before trying again to install from the dev list - Validation failed once more.
Are hashes actually updated when I click on _Add hash_ when I release a new plugin version (binaries respectively)?
Thanks.

BR

**Comment by bruderstein** [comment]
The install on the dev list works fine for me, and the validation URL is returning OK for the the ComparePlugin.dll file - https://nppxml.bruderste.in/pm/validate?md5=bc2bc5ef1bd504fa1af10096fe414ae0

This _could_ be your IE cache, caching outdated response. Check the above URL in IE - if it doesn't say "ok",  try clearing your cache, then retry installing.

**Comment by chcg** [comment]
@pnedev 
Hi Pavel, 
I readded the validation for the dll files. Could you retest with the current dev list again. As Dave said at least with a fresh installation that wen't ok without a validation warning. I used version 1.4.4, and 1.4.3 both are ok.

Regards,
 Christian

**Comment by pnedev** [comment]
( @bruderstein , @chcg )
Hi Dave and Christian,

I tried on native Win7 machine and the validation went just fine. I just tried again on my Linux setup under Wine - the problem persists.
Perhaps Wine is not handling properly some of the Win32 APIs I can't explain it otherwise.
I consider the problem resolved for now, Thank you both for helping with this.

BR

**Comment by chcg** [comment]
@pnedev 

MD5 is on file is requested here:
https://github.com/bruderstein/nppPluginManager/blob/master/libinstall/src/Validate.cpp#L18
and hashing is done based on win crypto api here:
https://github.com/bruderstein/nppPluginManager/blob/master/libinstall/src/md5.cpp
, but return value is not checked and therefore if wine doesn't support the api there exists also the option that the MD5 sum couldn't be calculated at all and maybe some random value is send to the server. 
In this case the error message could be more precise what exactly failed.

Do you face the same issue e.g. for nppexec plugin?

**Comment by pnedev** [comment]
@chcg 
Hello Christian,

That makes sense.
I just tried getting NppExec - it fails the same way.

BR
