### ISSUE TITLE
When will plugin manager be added or available for the 64x version of plus plus?

### ISSUE THREAD

**Issue by julesmanson** [bruderstein/nppPluginManager#44]
I noticed that a prerelease is available but according to feature request page it doesn't seem to be completed yet. Please don't take this message as ungrateful or thankless because the opposite is true. Instead take this message as to just how much people really do depend on the generosity of the open source community of developers as yourself.

Here is the link for reference: https://github.com/bruderstein/nppPluginManager/issues/7

**Comment by chcg** [comment]
Without the server support to manage x64 plugins the x64 client is of limited usage, as it just could display the already installed plugins and releasing that x64 version might confuse people more than it helps.

This first release just adds the possibilty to find x64 plugins in the list from the server, no functional changes or new features. Also the next release probably is just for bugfixes.
