### ISSUE TITLE
Plugin Manager does not support windows7 64 bit

### ISSUE THREAD

**Issue by 503718696** [bruderstein/nppPluginManager#47]
Plugin Manager does not support windows7 64 bit

**Comment by bruderstein** [comment]
See #7

**Comment by sm4rk0** [comment]
@bruderstein an [ISSUE_TEMPLATE.md](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) with a reminder to submitter to search for existing issues before creating a new one would help prevent duplicates like this. A comment in it, like one in [ansible/ansible](https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md) would result in a text not visible in resulting bug even if it's not deleted, but visible while creating it:
```
<!---
Verify first that your issue/request is not already reported on GitHub.
Also test if the latest release, and master branch are affected too.
-->
```

**Comment by chcg** [comment]
Added an ISSUE_TEMPLATE.md with https://github.com/bruderstein/nppPluginManager/commit/89aac7570125220f02bc6966e8b99e29b5606413
