### ISSUE TITLE
"Available plugins" list is empty 

### ISSUE THREAD

**Issue by radarmanau** [bruderstein/nppPluginManager#48]
### Description of the Issue

I installed PluginManager as per your instructions. Started Notepad++. PluginManager appears in the Plugins pulldown menu. I then select it however the List of plugins available under the "Available" tab is emply. Wondering what I need to do or check to rectify the issue.

Notepad++ x64 bit (v7.3.3) installation on Win10 x64. 

I created an empty "allowAppDataPlugins.xml" file as suggested under the settings button.

![npp plugin mgr-1](https://cloud.githubusercontent.com/assets/26447369/23976808/df960534-0a35-11e7-85e8-7bcb58237cb7.jpg)
![npp plugin mgr-2](https://cloud.githubusercontent.com/assets/26447369/23976810/df99540a-0a35-11e7-92e9-ff01d64ab581.jpg)
![npp plugin mgr-3](https://cloud.githubusercontent.com/assets/26447369/23976809/df979be2-0a35-11e7-9d23-1d100f2ca38b.jpg)
![npp plugin mgr-4](https://cloud.githubusercontent.com/assets/26447369/23976807/df95c06a-0a35-11e7-95c0-d4ac63eafb52.jpg)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by bruderstein** [comment]
There is no list of x64 plugins yet - we're working on server support. See #7
