### ISSUE TITLE
No Plugins shown

### ISSUE THREAD

**Issue by z2z** [bruderstein/nppPluginManager#49]
### Description of the Issue

No plugins found in 64 bit version.
### Steps to Reproduce the Issue

1. Download plugin https://github.com/bruderstein/nppPluginManager/releases/download/v1.4.4/PluginManager_v1.4.4_x64.zip
2.  Extract and Run Np++ (with or without Admin)
3. Open Plugin Manager 

### Expected Behavior
Display list of plugins

### Actual Behavior
No new plugins available
https://snag.gy/wNmOuD.jpg

### Debug Information

Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll PluginManager.dll 

1.4.4.0

**Comment by chcg** [comment]
see #48 , use #7 for further discussion/information
