### ISSUE TITLE
Plugin manager crash

### ISSUE THREAD

**Issue by tgotic** [bruderstein/nppPluginManager#51]
Plugin manager crashes if cannot save downloaded file.
Please find attached patch file to fix this issue.
[libinstall.patch.txt](https://github.com/bruderstein/nppPluginManager/files/868931/libinstall.patch.txt)

**Comment by chcg** [comment]
Issues addressed by the patch:
- Missing file pointer return value check
- Unchecked decrements on unsigned aka size_t vars with risk of wrap around

**Comment by chcg** [comment]
@tgotic Do you have an example which plugin download triggers this code path in DirectLinkSearch.cpp?

**Comment by chcg** [comment]
According to dave the DirectLinkSearch stuff was used for sourceforge in the past, but is currently not used any more, so couldn't be tested in real life right now. I tested it with the debugger as far as possible, but I'm not completely sure no further issues are hidden there.

**Comment by chcg** [comment]
fixed with v1.4.5
