### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by dail8859** [bruderstein/nppPluginManager#53]
The certificate for https://bruderste.in/npp/pm/ is expired.

Firefox reports  `The certificate expired on Friday, March 31, 2017 7:16 PM. The current time is Friday, April 07, 2017 11:49 AM.`

**Comment by bruderstein** [comment]
Resolved - there's something up with the Let's Encrypt setup that doesn't restart the nginx process. Certificate is correctly renewed, just not restarted.

**Comment by bruderstein** [comment]
Thanks @dail8859 for reporting!

**Comment by dail8859** [comment]
Looks like this happening again:

> bruderste.in uses an invalid security certificate.
The certificate expired on May 30, 2017 at 7:51 PM. The current time is June 2, 2017 at 8:31 AM.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
