### ISSUE TITLE
AppData plugins are not handled correctly

### ISSUE THREAD

**Issue by bruderstein** [bruderstein/nppPluginManager#54]
### Description of the Issue
When plugins are installed in both the appdata and usual `notepad++\plugins` folders, then plugin manager seems to take a different view of how to handle this as N++ does.

This _may_ also be an issue when plugin manager itself is installed in both locations - needs further investigation.

**Comment by chcg** [comment]
See N++ code for loading Plugins at:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp

bool PluginsManager::loadPlugins(const TCHAR *dir)

called by LRESULT Notepad_plus::init(HWND hwnd)

```

	// Load plugins firstly from "%APPDATA%/Notepad++/plugins"
	// if Notepad++ is not in localConf mode.
	// All the dll loaded are marked.
	bool isLoadFromAppDataAllow = ::SendMessage(_pPublicInterface->getHSelf(), NPPM_GETAPPDATAPLUGINSALLOWED, 0, 0) == TRUE;
	const TCHAR *appDataNpp = pNppParam->getAppDataNppDir();
	if (appDataNpp[0] && isLoadFromAppDataAllow)
		_pluginsManager.loadPlugins(appDataNpp);

	// Load plugins from its installation directory.
	// All loaded dll will be ignored
	_pluginsManager.loadPlugins();
```

**Comment by bruderstein** [comment]
Yes, but, if you try it, you'll see that the AppData wins. The reason is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp#L119

loadPlugin actually checks for a unique filename, and if it's been loaded before, it just skips it:
```c
int PluginsManager::loadPlugin(const TCHAR *pluginFilePath, vector<generic_string> & dll2Remove)
{
	const TCHAR *pluginFileName = ::PathFindFileName(pluginFilePath);
	if (isInLoadedDlls(pluginFileName))
		return 0;
       // ...
}
```

```c
void addInLoadedDlls(const TCHAR *fullPath, const TCHAR *fn) {
	_loadedDlls.push_back(LoadedDllInfo(fullPath, fn));
}
```

Plugin manager is actually doing _almost_ the same thing, in that AppData wins, but it doesn't observe the only-one-of-a-filename rule, and uses a only-one-of-a-given-`pluginName` rule. 

So, actually, I think we're being almost as close to "right" as we can be here - I'm not sure how we'd represent a duplicate name plugin with different DLLs names. 

The only issue I see, is if "Install for all users" is selected and the plugin is currently in AppData, then the older version will still win. This is an issue, but a relatively minor one as it's pretty obscure.  We should however probably delete the AppData version if that's where it is at the moment.

I think fixing this is a bigger job, so I'm tempted to go with just #55 for 1.4.5, and we'll aim to add some integration tests around this so that we can check we don't break anything - this issue feels like a bigger change.

WDYT?

**Comment by chcg** [comment]
Yes, I think we should first tackle the issues we could fix and understand. And the go for this one.

**Comment by brightghost** [comment]
Just to provide some more detail per https://github.com/bruderstein/nppPluginManager/issues/45#issuecomment-293038089 , this issue appears to be also affecting the PluginManager, itself. In my testing Plugin Manager is deciding to prompt for a Plugin Manager update based upon the version found in Program Files, even though an already up-to-date version is being loaded from AppData. Additionally, when running as a non-admin user, the updater in fact fails to update the Program Files DLL, even after elevating.

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll Explorer.dll Python Indent.dll TagLEET.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by bruderstein** [comment]
Confirmed - I can reproduce - https://github.com/bruderstein/nppPluginManager/issues/45#issuecomment-293041153

Great sleuthing everyone :)

**Comment by bruderstein** [comment]
I think I actually might have a quick fix for this, if we can get this tested quickly, we can push this out, that would save most people upgrading twice in quick succession :+1:

**Comment by CollinChaffin** [comment]
Hey Dave I was out of pocket a few days didn't even realize you had opened this and don't know how I missed that the loop issue had already been entered.  I just commented too in the other issue #52  but as much as I was and have re-tested the APPDATA scenario I'm really pleased to confirm my testing now as far as this issue and the loop issue #45 with 1.4.8 looks great!

Also, just logged off my testing VM for these issues and have to say the addition of (below) this detail and visual confirmation/acknowledgelment that plugmgr has properly detected the presence of allowAppdataPlugins.xml and that it is running under that configuration is awesome too!

![snag_4-14-2017_23-47-57](https://cloud.githubusercontent.com/assets/9301483/25060900/42e71084-216e-11e7-9a61-08de6c003aaa.png)

**Comment by bruderstein** [comment]
I think we can say this is fixed then :)
