### ISSUE TITLE
Confirmation pop-up window unresponsive when file open in other view

### ISSUE THREAD

**Issue by decoderman** [bruderstein/nppPluginManager#63]
### Description of the Issue
When I want to install a plugin where the integrity cannot be validated (say CustomizeToolbar), the ‘copy file anyway’ popup is not responding, not even to the ‘x’. ‘Yes’ or ‘No’ don’t work and the parent downloader popup cannot be cancelled.
You have to quit NPP in Task Manager to get out of it.

### Steps to Reproduce the Issue
1. Have two files open in NPP and move one file to “Other View”.
2. Open Plugin Manager and make an action that requires NPP to open a pop up to ask you for further action, e.g. restart or where file integrity cannot be verified.
3. You will not be able to confirm, deny or close that pop up as the focus is on the second View file in the background.
4. Only way to close pop up is to force quit NPP in Task Manager

### Expected Behavior
Expected behaviour is one can click the Buttons. This works with only one View Window populated.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll AutoSave.dll ccc.dll ColorPicker.dll ComparePlugin.dll LocationNavigate.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll TakeNotes.dll

**Comment by chcg** [comment]
@decoderman Which version of did you use for this? Did you already test with v1.4.6 or newer or still v1.4.3? Thanks for adding the issue description also here.

**Comment by decoderman** [comment]
It happened on a previous version when I updated to currently installed 1.4.5.
That's when it downed on me that it might have to do with the second view window.
I always have two views open. I'll update to 1.4.6, although that is not an option through the GUI atm.

**Comment by decoderman** [comment]
I just manually updated to 1.4.8, the problem persists.
Steps to recreate: 
Two files open, move one file to other view.
Install plugin, say Column sorting.
Confirmation that installation steps need to be completed cannot be clicked.

**Comment by bruderstein** [comment]
Hm... i can't reproduce this.

Can you double check the version of plugin manager running in the `Plugins -> Plugin Manager -> About` box?  (wondering if appdata version is running)

**Comment by decoderman** [comment]
Version 1.4.8.0, I have two graphic cards with four monitors, if that makes a difference.

**Comment by decoderman** [comment]
Found the reason why:
You need to install the Plugin AutoSave (1.6), then it happens, takes the focus away if two views are used.

I'm not sure this needs fixing as I now know to close the second view when I use the Plugin Manager. A rare combination of plugins and use case maybe.
I consider this Issue closed.

**Comment by decoderman** [comment]
I might add, that AutoSave is set to save all open files when focus on NPP is lost.
This will be in conflict with the pop up confirmation window.

**Comment by bruderstein** [comment]
Wow, great find! I can reproduce now. I've tracked this through, and I can't actually see why - we're setting the parent correctly, there doesn't seem to be another dialog opened by AutoSave - in fact, the N++ window itself has focus and you can even change the files that are open. Only File -> Exit from the menus works though.

It's pretty unlikely an issue with AutoSave, but I can't see what PM is doing wrong, if anything. The code for autosave isn't open source unfortunately, so only the author can tell.

**Comment by decoderman** [comment]
Glad you can recreate it as well!
As I said, this is not likely to happen to others as it needs that rare combination to be true for that behavior to kick in. 
But to be on the save side, ask @Franco-Stellari on the NPP board, he might be able to shed some light on the cause of this.
