### ISSUE TITLE
Validation error while updating Plugin Manager v1.3.5

### ISSUE THREAD

**Issue by joachimmelcher** [bruderstein/nppPluginManager#65]
### Description of the Issue
I am using Notepad++ (32 bit) v7.3.3 with pre-installed Plugin Manager v1.3.5. When I try to update the Plugin Manager, the update fails with a validation error.

Searching the open and closed issues, I found:
- Issue #22: The issue poster also has a problem with updating Plugin Manager v1.3.5. But instead of a restart, I get a validation error message.
- Issue #57: As far as I understand the issue, it also (indirectly) deals with a validation problem (wrong hashes) and was the cause of the recent Plugin Manager updates (to latest version 1.4.9). Can there be a connection to my problem?

### Steps to Reproduce the Issue
1. Start Notepad++ v7.3.3
2. Choose menu "Plugins" -> "Plugin Manager" -> "Show Plugin Manager"
3. Wait for download of plugin list
4. Go to tab "Updates"
5. Select "Plugin Manager"
6. Click button "Update"

### Expected Behavior
Successful update of Plugin Manager to version 1.4.5 (shown in update list) or even 1.4.9 (latest release of Plugin Manager)

### Actual Behavior
After the download of the updated Plugin Manager, an error message appears: "It has not been possible to validate the integrity of 'PluginManager.dll' needed to install or update a plugin. Do you want to copy this file anyway (not recommended)?" (see also attached screenshot)

![screenshot with error message](https://cloud.githubusercontent.com/assets/4741424/25140305/1bad07a4-2460-11e7-9de5-cf216d59d27e.png)

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll
Plugin Manager v1.3.5.0

**Comment by bruderstein** [comment]
It was actually an issue with the old location of the valid hash list that hadn't been updated after the push to 1.4.5. Fixed now, huge thanks for reporting!
