### ISSUE TITLE
Unable to validate integrity of any plugin on install

### ISSUE THREAD

**Issue by jameswilddev** [bruderstein/nppPluginManager#70]
### Description of the Issue

I don't seem to be able to install any plugins; I've tried installing JSTool, JSLint, XML Tools and all of them state that "It has not been possible to validate the integrity of '...' needed to install or update a plugin."

### Steps to Reproduce the Issue

1. Plugins->Plugin Manager.
2. Tick JSTool, JSLint or XML Tools.
3.  Click "Install".

### Expected Behavior

Plugin installs.

### Actual Behavior

An error message appears stating "It has not been possible to validate the integrity of '...' needed to install or update a plugin.".

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll PluginManager.dll 

![plugin](https://cloud.githubusercontent.com/assets/3138458/25564178/514c7310-2da5-11e7-8906-6744088ab171.png)

**Comment by bruderstein** [comment]
Thanks for the report - should be fixed now.

**Comment by jameswilddev** [comment]
Can confirm, thanks for the help!

**Comment by DARKFiB3R** [comment]
This is happening for me with the latest update.
