### ISSUE TITLE
JSTool x64 not visible

### ISSUE THREAD

**Issue by rustyx** [bruderstein/nppPluginManager#71]
PluginManager 1.4.9 x64 does not show the JSTool plugin, which does have a x64 version. Please add it to the list!

![notepad++ plugin manager x64](https://rustyx.org/temp/pmgr64.png)

**Comment by MAPJe71** [comment]
You should contact the author of the plugin for this at the [JSTool GitHub repository](https://github.com/sunjw/jstoolnpp).

**Comment by chcg** [comment]
@rustyx The correct repo to update the x64 plugin list is https://github.com/bruderstein/npp-plugins-x64, you could also add PRs for plugins which are missing in the list.

I added JSTool with https://github.com/bruderstein/npp-plugins-x64/commit/6593069b2f372f6bc30bf39cda3305a7ab1bee2e
