### ISSUE TITLE
Why is an older version of the Plugin Manager still shipped with npp?

### ISSUE THREAD

**Issue by Gitoffthelawn** [bruderstein/nppPluginManager#72]
Is there any reason why an outdated version of the Plugin Manager is still shipped with npp?

**Comment by chcg** [comment]
Objection of don ho (maintainer of N++) against the ad for the support of the server infrastructure.

**Comment by Gitoffthelawn** [comment]
Oh man, that tiny little ad that supports the requisite server?

I understand his objection, but it's hard to understand the logic that it's better to use outdated code instead of a tiny little static ad that is hidden in a sub-interface.

I don't like ads in my software, but without a server, how does this software work?!

Maybe Don can find a free server.

BTW, you could always terminate the existing server and open a new one that is only accessible via the latest version. ;)

**Comment by Gitoffthelawn** [comment]
@chcg BTW 2, intrusive ads (switching between different ads automatically without even refreshing the page) are present on https://notepad-plus-plus.org/download/v7.4.2.html
