### ISSUE TITLE
Plugin list not getting updated

### ISSUE THREAD

**Issue by dail8859** [bruderstein/nppPluginManager#73]
This is in regards to the 32-bit plugin list, I haven't tried the 64-bit plugin manager at all.

### Description of the Issue
Last I knew the plugin list was supposed to get updated every 2 weeks. But it appears it hasn't been updated in nearly 2 months. **Note**: using the "development plugin list" seems to work as expected.

### Steps to Reproduce the Issue
1. Go to `%APPDATA%\Notepad++\plugins\config` and delete the `PluginManager.*` files (the ini, xml, and zip file)
2. Start Notepad++
3. Open the Plugin Manager.
4. If you login to the plugin admin website and look at https://npppm.bruderste.in/plugins/?order=lastmod then you will see that on 2017-04-20 the AutoCodepage plugin was added, but does not show up in the list (any changes after this do not show up either). The previous change to the list took place on 2017-04-18 which seems to be fine.

### Expected Behavior
To get an updated list every 2 weeks.

### Actual Behavior
It seems the list has not been updated since sometime between April 18th and April 20th.

### Debug Information
```
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection.dll DoxyIt.dll DSpellCheck2.dll ElasticTabstops.dll LuaScript.dll NppConverter.dll NppExport.dll PluginManager.dll Scintillua++.dll SurroundSelection.dll 
```

Plugin Manager version 1.4.9.0

**Comment by chcg** [comment]
@bruderstein Please have a look at the server.

**Comment by bruderstein** [comment]
Fixed. I've hopefully fixed this permanently now. It should be scheduled for odd weeks (`date +%W`) on Monday at 20:00 UTC. I'll set a reminder to check it a week on Monday.
