### ISSUE TITLE
NppExport 64 bits not listed in available and without info in installed

### ISSUE THREAD

**Issue by warmth** [bruderstein/nppPluginManager#74]
Here is the link to latest release of NppExport 64 bits: https://github.com/chcg/NPP_ExportPlugin/releases

![image](https://user-images.githubusercontent.com/237218/27821665-5ece1bb6-60a3-11e7-9c42-3f6fbc87d344.png)

**Comment by bruderstein** [comment]
See https://github.com/bruderstein/npp-plugins-x64 for how to add this.

**Comment by chcg** [comment]
@warmth Added with https://github.com/bruderstein/npp-plugins-x64/commit/c2800e04a7e814376a2f52a3ceb240b23850fbe7
