### ISSUE TITLE
NppConverter.dll validation error

### ISSUE THREAD

**Issue by TriStarGod** [bruderstein/nppPluginManager#76]
### Description of the Issue

I am using Notepad++ (32 bit) v7.4.2 with Plugin Manager v1.4.9 and Converter. When I try to update the Converter, the update fails with a validation error.

### Steps to Reproduce the Issue

1. Start Notepad++
2. Choose menu "Plugins" -> "Plugin Manager" -> "Show Plugin Manager"
3. Wait for download of plugin list
4. Go to tab "Updates"
5. Select "Plugin Manager"
6. Click button "Update"

### Expected Behavior

To update with validation of dll

### Actual Behavior

Displays "It has not been possible to validate the integrity of 'NppConverter.dll' needed to install or update a plugin. Do you want to copy this file anyway (not recommended)?" Yes or No?

### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by chcg** [comment]
@TriStarGod Checksum is calculated locally and send to the server to check against the stored one. I don't face this issue on reinstalling converter 4.2.1. So most probably the server was not accessible at that time or there was a problem with the internet connection.

Is this issue reproducible?

**Comment by TriStarGod** [comment]
On two computers on separate networks, I faced this issue. On one, I went ahead. On the other, I didn't update it. However, I did reinstall on the second one and it updated that plugin without complaints. It might have just been version v7.4.2.
