### ISSUE TITLE
UTF characters not rendered correctly in plugin information

### ISSUE THREAD

**Issue by rbsec** [bruderstein/nppPluginManager#77]
### Description of the Issue
UTF characters in the plugin information are not rendered correctly in plugin manager when the plugin is viewed (for example, when trying to install a new plugin).

The author of the [Npp Xml Treeview](https://github.com/joaoasrosa/nppxmltreeview/search?utf8=%E2%9C%93&q=rosa&type=) plugin is `João Rosa`  but this is shown in Plugin Manager as `JoÃ£o Rosa`

![image](https://user-images.githubusercontent.com/3534212/29514572-f61bee70-8660-11e7-894c-8f2f70bb8b3f.png)

The plugin still installs and works as expected, so this is a minor issue.

### Version Information
Plugin manager version : 1.4.9.0 (x64)
Notepad++ version: 7.4.2 (x64)
OS: Windows 10 1703 Enterprise (x64)

**Comment by chcg** [comment]
This issue is caused by the usage of UTF-8 in the plugin xml list and the handling as wchar_t aka UFT-16 in the tinyxml parsing. So some transformation with e.g. MultiByteToWideChar() is missing here.
