### ISSUE TITLE
Installation of Plugin Manager failed

### ISSUE THREAD

**Issue by jenokizm** [bruderstein/nppPluginManager#79]
Hi, i have same error https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3313 when update

```
---------------------------
Installation Error
---------------------------
Installation of Plugin Manager failed.
---------------------------
ОК   
---------------------------
```
Windows 10 x64, Notepad++ 7.5.1 running as admin
ps for example, also soma action, with the same version Notepad++ on windows 7 x64 does not cause any errors and works correctly. Maybe you have poor compatibility with Windows 10

**Comment by danicoolpak17** [comment]
@jenokizm the plugin manager support is not working properly. I have tried to install 32 bit version on x64 and install all the required plugins. you can use the same. If you like.

**Comment by chcg** [comment]
@jenokizm 
- Which version of PM have you combined with N++ 7.5.1. 
- Are N++ and PM both 64bit or 32bit?
- How did you install PM? howto see https://htmlpreview.github.io/?https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html#install

**Comment by jenokizm** [comment]
Guys, it's been 2 months now I do not remember anything and now I do not care.

**Comment by chcg** [comment]
So I will close it for now.
