### ISSUE TITLE
%1 is not a valid windows application

### ISSUE THREAD

**Issue by BenCat07** [bruderstein/nppPluginManager#8]
so...... i tried to start notepad+ (had to install this plugin Manually for some reason) and then i got this error when it tried to import the dll of the plugin. Could domeone help me? and yes i had to mess with my registery because Some stuff was broken (.exe and exefile is now "1%"*1 or something like that) would be nice if someone could help. thanks. Running Windows 10

**Comment by BenCat07** [comment]
maybe i'll try the ascii version? if it works i'll close this.

**Comment by bruderstein** [comment]
As long as you've got a reasonably new version of Notepad++, you won't have the ANSI version.

The current version of this plugin is a beta, if you just want to use Notepad++, use the one bundled with it for now.  And you probably need to look at another machine to check what your registry should look like - you shouldn't need to change anything for Notepad++ to work.

I'm going to close this, as it doesn't sound like this is an issue with PM.

**Comment by sm4rk0** [comment]
@BenCat07 Hint: The same happened to me when I copied the nppPluginManager v1.4.1 into 64-bit Notepad++ plugins directory (just out of curiosity). Notepad++ said it will disable the plugin but I had to remove it manually (maybe UAC). Download the 32-bit Notepad++ [as](https://notepad-plus-plus.org/news/notepad-7-released.html)
> not all binaries are available in 64-bits - only a few plugins (done by me) are x64 ready

**Comment by BenCat07** [comment]
Still bricked. LOL i'll try @sm4rk0 tip

**Comment by BenCat07** [comment]
because the Plugin manager wasn't installed with notepad++.....

**Comment by BenCat07** [comment]
FINALLY works. i Installed the 32 bit version and somehell got my old Plugins back after setting the xtra Plugin folder to APPDATA/(BLAH). thought i lost the data but i must have loaded APPDATA on my pc too after loosing everything in my PC error Reset. lel

**Comment by BenCat07** [comment]
After updating my windows the bug dissapeard


2016-10-24 18:49 GMT+02:00 Benjamin Dawkins <bencat07@gmail.com>:

**Comment by BenCat07** [comment]
Alright i found out what happend: I had eclipse didn't install my java
correctly and it open a "what do you want to open this with" Window. i
thiought something was broken and changed the fitting keys in the Regestry
to a value that resets it to normal, but that value accidently ruined the
dll's for notepad. Means: Bad Programming or Windodge is too dumb.

Thanks anywys

2016-10-11 21:02 GMT+02:00 Marko Stanković <notifications@github.com>:
