### ISSUE TITLE
Plugin manager is not following redirects

### ISSUE THREAD

**Issue by tberne** [bruderstein/nppPluginManager#81]
### Description of the Issue
Plugin manager is performing the following HTTP request to get the plugin list:

    GET http://downloads.sourceforge.net/project/npppluginmgr/xml/plugins.md5.txt HTTP/1.1
    User-Agent: Notepad++/Plugin-Manager;v1.0.8.0
    Host: downloads.sourceforge.net
    Accept: */*
    Connection: Keep-Alive

And this request is returning the following response (body ommited):

    HTTP/1.1 302 Found
    Server: nginx
    Date: Wed, 22 Nov 2017 13:26:31 GMT
    Content-Type: text/html; charset=UTF-8
    Content-Length: 327
    Connection: close
    content-disposition: attachment; filename="plugins.md5.txt"
    Set-Cookie: sf_mirror_attempt="npppluginmgr:ufpr:xml/plugins.md5.txt"; expires="Wed, 22-Nov-2017 13:28:31 GMT"; Max-Age=120; Path=/
    Location: https://ufpr.dl.sourceforge.net/project/npppluginmgr/xml/plugins.md5.txt

Then, no further request to `https://ufpr.dl.sourceforge.net/project/npppluginmgr/xml/plugins.md5.txt` is performed.

The plugin list shows no plugins available.

### Steps to Reproduce the Issue
1. Open Notepad++
2. Open plugin manager
3. No available plugin is shown

### Expected Behavior
Plugin list is displayed

### Actual Behavior
No available plugin is shown

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by bruderstein** [comment]
Please update to the newest version of plugin manager, that fixes this issue. See the releases tab here
