### ISSUE TITLE
Not working yet?

### ISSUE THREAD

**Issue by qwadzie** [bruderstein/nppPluginManager#82]
### Description of the Issue
ON 64 bit GUP.exe, it says it's trying to install a 32 bit version over the 64 bit version, so I had to say 'No' until I'm sure it will leave my 64 bit version alone, or update it.
ON 64 bit GPUP.exe, it got some error.  It did run the update window though with only 1 update.  How do I install new plugins? (are they available on 64 bit version yet?)
Super. thanks.

### Steps to Reproduce the Issue

1. download V1.4.9_64 zip
2. copy folders to nppp install folder in 'Program Files' on 64 bit windows 7 machine.
3. run GUP.exe or GPUP.exe in 'GUP

### Actual Behavior
in GPUP is says invalid parameters passed to plugin updater GPUP. and gives usage with -w, -a, etc.
in GUP.exe it says an update package is available do I want to download it but downloads and installs the 32 bit version.

**Comment by bruderstein** [comment]
You never need to run gpup.exe yourself. It's run as part of the install/update process when you install or update a plugin, but it happens automatically in the background.

**Comment by chcg** [comment]
Further note: GUP is not part of PM, but notepad++ itself, see also https://github.com/gup4win/wingup.

For the available 64bit plugins, see the GUI or https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins64.xml

PM is available from within N++ under Plugins->Plugin Manager->Show Plugin Manager after the manual installation
