### ISSUE TITLE
Cannot login to https://npppm.bruderste.in/plugins

### ISSUE THREAD

**Issue by Predelnik** [bruderstein/nppPluginManager#83]
Not sure if this is correct place to report problem with admin's system but still
![image](https://user-images.githubusercontent.com/2133957/34349510-7e6e4c4e-ea22-11e7-86c6-8f63cca62b11.png)

**Comment by Predelnik** [comment]
Apparently now it works.

**Comment by chcg** [comment]
@Predelnik Unfortunately that is happening from time to time. Seems to be a resource issue of the server which typically goes away some minutes later. That could just be fixed by Dave.
