### ISSUE TITLE
Cannot download list of plugins

### ISSUE THREAD

**Issue by Cris70** [bruderstein/nppPluginManager#92]
### Description of the Issue
I cannot download the list of plugins. 
I am using Notepad++ v7.5.4 (64 bit) and Plugin Manager v1.4.10.0.

When opening plugin manager I get a dialog box saying "There was an error downloading the plugin list(...)". It makes no difference if I chose to use the development or the regular list, and it also makes no difference if I use HTTP or HTTPS.

Note that I am behind a corporate proxy, but if I input the list url (http://nppxml.bruderste.in/pm/xml/plugins64.zip) into IE on the same computer where Notepad++ is, I can download the file.

The proxy is obviously configured correctly (given that I can download from IE).

### Steps to Reproduce the Issue
1. Open Notepad++
2. Open the plugin manager
3. Get the error dialog box

### Expected Behavior
I expect not to see the dialog box and instead see the plugin list filled.

### Actual Behavior
I got an error dialog box (see attached image)

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 

![image](https://user-images.githubusercontent.com/5107224/36538540-3289c076-17d4-11e8-9973-7d01585e1ab2.png)

![image](https://user-images.githubusercontent.com/5107224/36538590-684e07c6-17d4-11e8-8243-e12089d4f4da.png)

**Comment by kgbm3** [comment]
First of all, _who in the world_ is using MSIE (LOL): what's wrong with you? o.0 

As far as your download (non-issue) problem goes, there are -actually- three EXEs that require a connection, so perhaps that could be the issue: 

https://s14.postimg.org/4svazrbpt/gpup.png

**Comment by chcg** [comment]
@Cris70 See #91, maybe this also affected your list download. Do you still observe the issue?

**Comment by Cris70** [comment]
@kgbm3 I DO NOT use IE. FWIW I don't even use Windows. But this is something related to a VM I *have* to use at work (you see I mentioned being behind a corporate proxy?) where I'm not entitled to install anything besides what's supposed to be there already, so you might want to ask my employer why on earth they want to stick with IE ;-)

Regarding the look, that is a Windows Server 2012 with what they (M$) call "classical look" (IIRC). Another obligated choice. Policy, you know.

Last, we do not have the firewall enabled locally on the VMs, because there's a centralized firewall that I have no control on, for which I have to use a proxy. Obviously, being centralized, it works based on network rules, not based on programs, so if IE passes through then every other program on that VM should be able to pass, too (provided it is able to correctly use an HTTP proxy, that is).

**Comment by Cris70** [comment]
@chcg yes, unfortunately I still observe the issue :-(

**Comment by kgbm3** [comment]
Yeah, yea, that (reply) had been a bit hasty of me, trying to make a bad joke..:) Um, the #91 issue is linking to issue #88 which we know already that: "[PM is just reusing the settings of the IE](https://github.com/bruderstein/nppPluginManager/issues/88#issuecomment-360523449)" 

... So, it's a Windows SNAFU from the looks of it. The worst idea Micro$oft had ever had (arguably, there are tons), integrating the web engine into the OS. :-s

**Comment by Cris70** [comment]
Thank you @kgbm3 , I'll wait and see if someone comes up with a bright idea on how to debug/fix this problem.
Speaking of debugging though... is there any way to see a log or something like that about what the plugin manager is trying to do when connecting?

**Comment by chcg** [comment]
@Cris70 You might could add some network tracer to check what is going on, see https://superuser.com/questions/414073/logging-individual-application-network-usage-in-windows-7. With the setting to use http it should be possible to see the complete tcp communication.

**Comment by Cris70** [comment]
Thank you @chcg . Actually it's now been working for a few days.
I don't know if it's due to something changed on my side (maybe my colleagues changed some firewall rule?) or something changed on the site hosting the plugins.
