### ISSUE TITLE
What does the _UNI suffix mean on the releases download page?

### ISSUE THREAD

**Issue by StingyJack** [bruderstein/nppPluginManager#93]
There is a _UNI and _x64 and I need x86.  Does it mean UNIversal or UNIx or something else?

**Comment by chcg** [comment]
Unicode. Previously there were two N++ 32bit versions one for ansi  and one for unicode. The last version for ansi is https://notepad-plus-plus.org/download/v5.9.6.2.html.

So _uni is the one you need.

**Comment by StingyJack** [comment]
ty
