### ISSUE TITLE
64-bit PluginManager can't install updates: Installation of DSpellCheck.exe failed.

### ISSUE THREAD

**Issue by rustyx** [bruderstein/nppPluginManager#98]
### Description of the Issue
Many plugins fail to install using the latest 64-bit PluginManager.

Are there any logs written? I couldn't find any.

How to debug this?

![pluginmanager_error](https://user-images.githubusercontent.com/1296899/36993415-0b04d0ee-20ae-11e8-834d-f86f24e59ab5.png)

**Comment by chcg** [comment]
@rustyx Which windows version? PM version 1.4.10? Which update did you try to install of dspellcheck 1.4.2?

Just tried the update of PM to 1.4.9 ->1.4.10 and DSpellCheck 1.4.0 -> 1.4.2 without problems. Both are hosted on Github. Could you access https://github.com/Predelnik/DSpellCheck/releases/download/v1.4.2/DSpellCheck_x64.zip without problems?

**Comment by rustyx** [comment]
Something strange is happening in WinInet with the URL https://github.com/Predelnik/DSpellCheck/releases/download/v1.4.2/DSpellCheck_x64.zip

It does follow the redirect but the download never starts, instead INTERNET_STATUS_HANDLE_CLOSING is fired, then INTERNET_STATUS_REQUEST_COMPLETE, and subsequently HttpQueryInfo fails with ERROR_INVALID_HANDLE.

**Comment by rustyx** [comment]
Here's a complete sequence of notification events:

INTERNET_STATUS_HANDLE_CREATED
INTERNET_STATUS_DETECTING_PROXY
INTERNET_STATUS_RESOLVING_NAME
INTERNET_STATUS_NAME_RESOLVED
INTERNET_STATUS_CONNECTING_TO_SERVER
INTERNET_STATUS_CONNECTED_TO_SERVER
INTERNET_STATUS_CLOSING_CONNECTION,	LastError=ERROR_INVALID_FUNCTION
INTERNET_STATUS_CLOSING_CONNECTION
INTERNET_STATUS_CONNECTION_CLOSED
INTERNET_STATUS_CONNECTING_TO_SERVER
INTERNET_STATUS_CONNECTED_TO_SERVER
INTERNET_STATUS_CLOSING_CONNECTION,	LastError=ERROR_INVALID_PARAMETER
INTERNET_STATUS_CLOSING_CONNECTION
INTERNET_STATUS_CONNECTION_CLOSED
INTERNET_STATUS_HANDLE_CLOSING
INTERNET_STATUS_REQUEST_COMPLETE,	LastError=ERROR_INTERNET_SECURITY_CHANNEL_ERROR

**Comment by rustyx** [comment]
@chcg looks like you were right, this was related to the TLS settings. Somehow TLS 1.2 got unchecked in my Internet Properties. After enabling it everything is back to normal (though the sequence of WinInet events in that case is no good).

![Internet Properties TLS 1.2](https://user-images.githubusercontent.com/1296899/37055767-d949c2dc-2182-11e8-9dc7-7f6f4963a35a.png)

**Comment by chcg** [comment]
@rustyx  Thanks for the update how to resolve this issue.

**Comment by letownia** [comment]
I'll add that this also effects the latest 32-bit version of Notepad++. Enabling newer versions of TLS fixed the issue for me.
