### ISSUE TITLE
settings button overlay issue v1.4.10

### ISSUE THREAD

**Issue by einst3** [bruderstein/nppPluginManager#99]
### Description of the Issue
pluginmanager settings button under image till hover over. image not displayed in right place. see screenshot. npp 7.5.4 32-bit on win7 x64

### Steps to Reproduce the Issue
1 show pluginmanger
2 dialog shows settings button under graphic (bottom left)
3 mouse move over button, button shows on top of image. see screenshot

### Expected Behavior
image should be right of settings button

### Actual Behavior
button z-order under image till hover over button

### Debug Information
npp 7.5.4 32-bit on win7 x64
see screenshot 
![untitled](https://user-images.githubusercontent.com/7558232/37047404-ce1715b2-2138-11e8-97d4-71269439825e.png)

**Comment by chcg** [comment]
@einst3 Should look like #66, but after first resizing of the dialog the issue appears and stays until n++ is exited.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.11
